USE AccentureChallenge
GO
BEGIN TRANSACTION  

BEGIN TRY  
	-- CUSTOMERS
    INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Alberto Alcaraz','alberto.a@gmail.com')
	INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Bento Bonilha','bento.b@gmail.com')
	INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Catia Cardoso','cardoso.c@gmail.com')
	INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Danilo Dellamar','danilo.d@gmail.com')
	INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Elvira Ettoni','elvira.e@gmail.com')
	INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Fabio Ferreira','fabio.f@gmail.com')
	INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Gustavo Garcia','gustavo.g@gmail.com')
	INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Humberto Hamilton','humberto.h@gmail.com')
	INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Ingrid Iasmin','ingrid.i@gmail.com')
	INSERT INTO CUSTOMERS (FULL_NAME, EMAIL) VALUES ('Jairo Jaguar','jairo.j@gmail.com')
	-- PRODUCTS
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Boot','Shoes') -- 80 / 1
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Sneakers','Shoes') -- 60 / 2
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Flip flops','Shoes') -- 20 / 3
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Socks','Clothes') -- 10 / 4
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Hoody','Clothes')-- 70 / 5
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Underwear','Clothes') -- 30 / 6
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Shirt','Clothes') -- 40 / 7
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Shorts','Clothes') -- 25 / 8
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Coat','Clothes') -- 75 / 9
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Pants','Clothes') -- 50 / 10
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Necklace','Jewelry') -- 300 / 11
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Bracelet','Jewelry') -- 250 / 12
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Ring','Jewelry') -- 200 / 13
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Earing','Jewelry') -- 150 / 14
	INSERT INTO PRODUCTS (FULL_NAME, CATEGORY) VALUES ('Watch','Jewelry') -- 100 / 15
	-- ORDERS
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (1, DATEADD(M,-1,GETDATE()), 100.00) --1
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (1, DATEADD(M,-4,GETDATE()), 70.00) --2
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (1, DATEADD(M,-2,GETDATE()), 210.00) --3
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (2, DATEADD(M,-3,GETDATE()), 150.00) --4
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (2, DATEADD(M,-5,GETDATE()), 370.00) --5
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (2, DATEADD(M,-7,GETDATE()), 110.00) --6
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (3, DATEADD(M,-1,GETDATE()), 50.00) --7
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (3, DATEADD(M,-4,GETDATE()), 160.00) --8
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (3, DATEADD(M,-6,GETDATE()), 80.00) --9
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (4, DATEADD(M,-2,GETDATE()), 350.00) --10
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (4, DATEADD(M,-8,GETDATE()), 240.00) --11
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (4, DATEADD(M,-1,GETDATE()), 120.00) --12
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (5, DATEADD(M,-3,GETDATE()), 130.00) --13
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (5, DATEADD(M,-4,GETDATE()), 600.00) --14
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (5, DATEADD(M,-5,GETDATE()), 60.00) --15
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (6, DATEADD(M,-1,GETDATE()), 30.00) --16
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (6, DATEADD(M,0,GETDATE()), 90.00) --17
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (6, DATEADD(M,-9,GETDATE()), 140.00) --18
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (7, DATEADD(M,0,GETDATE()), 330.00) --19
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (7, DATEADD(M,-5,GETDATE()), 170.00) --20
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (7, DATEADD(M,-9,GETDATE()), 210.00) --21
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (8, DATEADD(M,-3,GETDATE()), 180.00) --22
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (8, DATEADD(M,-4,GETDATE()), 180.00) --23
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (8, DATEADD(M,-2,GETDATE()), 80.00) --24
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (9, DATEADD(M,-6,GETDATE()), 50.00) --25
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (9, DATEADD(M,-5,GETDATE()), 100.00) --26
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (9, DATEADD(M,-2,GETDATE()), 150.00) --27
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (10, DATEADD(M,0,GETDATE()), 110.00) --28
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (10, DATEADD(M,-8,GETDATE()), 220.00) --29
	INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (10, DATEADD(M,-3,GETDATE()), 330.00) --30
	-- ORDER_ITEMS
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (1, 10, 1, 50)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (1, 8, 2, 25)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (2, 7, 1, 40)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (2, 4, 3, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (3, 2, 2, 60)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (3, 6, 3, 30)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (4, 15, 1, 100)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (4, 10, 1, 50)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (5, 12, 1, 250)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (5, 2, 2, 60)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (6, 7, 2, 40)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (6, 4, 3, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (7, 3, 1, 20)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (7, 4, 3, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (8, 7, 2, 40)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (8, 1, 1, 80)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (9, 5, 1, 70)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (9, 4, 1, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (10, 12, 1, 250)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (10, 15, 1, 100)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (11, 3, 2, 20)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (11, 15, 2, 100)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (12, 5, 1, 70)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (12, 8, 2, 25)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (13, 2, 2, 60)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (13, 4, 1, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (14, 9, 4, 75)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (14, 11, 1, 300)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (15, 3, 2, 20)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (15, 4, 2, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (16, 3, 1, 20)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (16, 4, 1, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (17, 10, 1, 50)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (17, 7, 1, 40)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (18, 15, 1, 100)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (18, 3, 2, 20)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (19, 14, 2, 150)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (19, 6, 1, 30)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (20, 9, 2, 75)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (20, 4, 2, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (21, 13, 1, 200)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (21, 4, 1, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (22, 2, 2, 60)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (22, 6, 2, 30)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (23, 15, 1, 100)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (23, 1, 1, 80)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (24, 8, 2, 25)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (24, 4, 3, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (25, 6, 1, 30)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (25, 4, 2, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (26, 9, 1, 75)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (26, 8, 1, 25)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (27, 5, 2, 70)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (27, 4, 1, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (28, 10, 2, 50)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (28, 4, 1, 10)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (29, 15, 2, 100)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (29, 3, 1, 20)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (30, 12, 1, 250)
	INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, PRICE) VALUES (30, 7, 2, 40)
END TRY  
BEGIN CATCH  
    SELECT   
        ERROR_NUMBER() AS ErrorNumber  
        ,ERROR_SEVERITY() AS ErrorSeverity  
        ,ERROR_STATE() AS ErrorState  
        ,ERROR_PROCEDURE() AS ErrorProcedure  
        ,ERROR_LINE() AS ErrorLine  
        ,ERROR_MESSAGE() AS ErrorMessage 
  
    IF @@TRANCOUNT > 0  
        ROLLBACK TRANSACTION  
END CATCH 
  
IF @@TRANCOUNT > 0  
    COMMIT TRANSACTION  
GO  